SET ECHO ON
SET FEEDBACK ON

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ProvxProd PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Prov PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE Prov (
  nit NUMBER NOT NULL,
  nombre VARCHAR2(100) NOT NULL,
  CONSTRAINT pk_prov PRIMARY KEY (nit),
  CONSTRAINT uq_prov_nombre UNIQUE (nombre)
);

CREATE TABLE ProvxProd (
  nit NUMBER NOT NULL,
  codigoProducto NUMBER NOT NULL,
  CONSTRAINT pk_provxprod PRIMARY KEY (nit, codigoProducto),
  CONSTRAINT fk_provxprod_prov FOREIGN KEY (nit) REFERENCES Prov(nit)
);

COMMIT;
